### ISSUE TITLE
Key error 1

### ISSUE THREAD

**Issue by Hrishaant** [faniAhmed/GoogleAdsTransparencyScraper#3]
I am getting an error like this 

please explain this error False
Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\gg1.py", line 31, in <module>
    detailed_ad = a.get_detailed_ad(advertiser_id, creative_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\GoogleAds\main.py", line 240, in get_detailed_ad
    ad_detail = self.get_breif_ads(advertisor_id, creative_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\GoogleAds\main.py", line 206, in get_breif_ads
    response = response.json()["1"]
               ~~~~~~~~~~~~~~~^^^^^
KeyError: '1'

**Comment by faniAhmed** [comment]
Share the keyword or adv id you were searching

**Comment by Hrishaant** [comment]
Hey, thank you for replying. this is the adv id "AR00604964697900318721".

**Comment by faniAhmed** [comment]
I tried the Advertiser ID, I am not getting any error. If you are still facing any error send me the particular Creative ID too.

**Comment by faniAhmed** [comment]
Closing this issue as no reply from your side, Let me know if the issue still exists
